jobs:
  test:
    env:
      MIX_ENV: test
    name: Erlang/OTP ${{ matrix.otp-version }} / Elixir ${{ matrix.elixir-version }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir-version }}
          otp-version: ${{ matrix.otp-version }}
      - uses: actions/checkout@v7
      - env:
          cache-name: mix compile
        name: Run actions/cache@v6 [${{ env.cache-name }}]
        uses: actions/cache@v6
        with:
          key: "${{ matrix.os }}:${{ env.cache-name }}:${{ hashFiles('mix.exs') }}"
          path: _build
          restore-keys: "${{ matrix.os }}:${{ env.cache-name }}:"
      - run: mix compile
      - run: mix format --check-formatted
      - run: mix test
    strategy:
      matrix:
        elixir-version: [1.20.3]
        os: [ubuntu-24.04]
        otp-version: [29.0.5]

name: CI

on:
  push:
    tags:
      - v[0-9]+
