jobs:
  test:
    env:
      MIX_ENV: test
    name: Erlang/OTP ${{ matrix.otp-version }} / Elixir ${{ matrix.elixir-version }}
    runs-on: ${{ matrix.os }}
    services:
      postgres:
        env:
          POSTGRES_PASSWORD: postgres
        image: ${{ matrix.postgres }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-retries 5
          --health-timeout 5s
        ports: ["5432:5432"]
    steps:
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir-version }}
          otp-version: ${{ matrix.otp-version }}
      - uses: actions/checkout@v7
      - env:
          cache-name: mix deps.get
        name: Run actions/cache@v6 [${{ env.cache-name }}]
        uses: actions/cache@v6
        with:
          key: "${{ matrix.os }}:${{ env.cache-name }}:${{ hashFiles('mix.lock') }}"
          path: dep
          restore-keys: "${{ matrix.os }}:${{ env.cache-name }}:"
      - env:
          cache-name: mix compile
        name: Run actions/cache@v6 [${{ env.cache-name }}]
        uses: actions/cache@v6
        with:
          key: "${{ matrix.os }}:${{ env.cache-name }}:${{ hashFiles('mix.exs', 'mix.lock') }}"
          path: _build
          restore-keys: "${{ matrix.os }}:${{ env.cache-name }}:"
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile
      - run: mix format --check-formatted
      - run: mix credo --all-priorities
      - run: mix dialyzer --format github
      - run: mix test
    strategy:
      matrix:
        elixir-version: [1.20.4]
        os: [ubuntu-24.04]
        otp-version: [29.0.6]
        postgres: ["postgres:17.11"]

name: CI

on:
  push:
    tags:
      - v[0-9]+
